from dataclasses import dataclass

# --------------------------------------------------------------------------- #
#                              TASK & REQUEST MODELS                          #
# --------------------------------------------------------------------------- #
@dataclass
class IoTTask:
    """Single task generated by an IoT device."""
    task_id: str
    cpu: float
    memory: float
    deadline: float            # seconds
    data_size: float           # MB
    priority: int              # 1 (low) … 5 (high)

    def __hash__(self):
        return hash(self.task_id)


@dataclass
class ResourceRequest:
    """Wrapper converting a task into a bid for the auctioneer."""
    device_id: int
    task: IoTTask
    bid_value: float           # utility declared by the device
